### ISSUE TITLE
Dates on resulted chart is not in consequence

### ISSUE THREAD

**Issue by VyacheslavLukin** [innosoft-pro/toggl-analyzer#7]
Somehow dates on chart after current date is start again
![image](https://cloud.githubusercontent.com/assets/7655121/22816562/ca778eb6-ef73-11e6-8706-cf23f9fc2537.png)

**Comment by gabriel-fallen** [comment]
I guess we should sort the arrays. It slipped my mind. I'll investigate and fix.
